language: php
php:
  - '5.6'
  - '7.0'
  - nightly
services:
  - mysql
dist: trusty
sudo: required
before_script:
  - composer install
  - mysql -u root -e "CREATE database fyp;"
  - php artisan key:generate
  - cp .env.example .env
  - php artisan migrate:fresh -v --seed
